# Created by Nelson Durrant, Sep 2024
#
# DOCKER COMPOSE FILE (RUNTIME IMAGE, ARM64)

services:
  agrobot:
    image: snelsondurrant/agrobot:latest
    platform: linux/arm64
    container_name: agrobot
    user: agrobot
    network_mode: host # Allows the container to communicate on the host's network
    privileged: true # Allows the container to access host devices
    volumes:
      - ../bag:/home/agrobot/bag:rw
      - ../config:/home/agrobot/config:rw
      - ../agrobot-ros2:/home/agrobot/ros2_ws
      - ../agrobot-teensy:/home/agrobot/teensy_ws
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /dev:/dev:rw # Grants access to all host devices
      - /run/udev:/run/udev:ro # Copies in our udev rules
    command: /bin/bash
    stdin_open: true  # Equivalent to -it in docker run
    tty: true  # Equivalent to -it in docker run
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm
