# Created by Nelson Durrant, Sep 2024

drive_controller:
  ros__parameters:
    kp: 2.0
    ki: 0.0
    kd: 0.0
    max_output: 100.0 # TODO: Add this functionality
    min_output: -100.0 # TODO: Add this functionality